[package]
name = "aoc2018"
version = "0.1.0"
authors = ["David Szotten <davidszotten@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
failure = "0.1.3"
itertools = "0.7.11"
regex = "1.1.0"
lazy_static = "1.2.0"
cached = "0.8.0"
